spring:
  datasource:
    spider:
      name: spider
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://10.240.132.150:3306/spider?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: spider
      password: YBNPnV55Z*uHwYue_TT5epK0!KzsGdQH
      driver-class-name: com.mysql.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      minEvictableIdleTimeMillis: 300000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
      #connectionInitSqls: set innodb_lock_wait_timeout=120
    metacollection:
      name: metacollection
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://10.240.132.150:3306/metacollection?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: crm
      password: ijydN4dpOLnwejZm3UXMl_8JbIMUHExD
      driver-class-name: com.mysql.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      minEvictableIdleTimeMillis: 300000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
      #connectionInitSqls: set innodb_lock_wait_timeout=120
    downcount:
      name: downcount
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://10.240.132.150:3306/down_count?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: crm
      password: ijydN4dpOLnwejZm3UXMl_8JbIMUHExD
      driver-class-name: com.mysql.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      minEvictableIdleTimeMillis: 300000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
      #connectionInitSqls: set innodb_lock_wait_timeout=120
api:
  auth: false

spider_admin: wanghujia@myhexin.com,lijie4@myhexin.com,zouying@myhexin.com,admin@myhexin.com,huangjiarong@myhexin.com,sunxufeng@myhexin.com,chenguanyu@myhexin.com,zhangcong2@myhexin.com

spider:
  prometheus-address: http://10.0.1.76:9090/api/v1/query
  vanish-address: http://10.0.1.159/webroot/lighthorse_sendv_msg.php
  upload:
    address: http://172.21.54.74:28000/edith/indicator/v1/detail/upload
    index-code: data_integration_trends
    email: huangjiarong@myhexin.com
  tpc:
      address: http://172.21.54.74:28000/tpc/outer/v1/index/edit?projectId=A10&time=%s&indexId=%s&indexValue=%s
      metric-id: 10805
      arrival-id: 4077
      lag-id: 10804
      app: cbas-spider-service
  alert:
      start-time: "05:00"
      end-time: "23:00"
      ip-white-list : "183.232.170.47,183.232.170.48,112.17.10.197,112.17.10.198,121.201.108.131,121.201.108.132,183.232.170.53,183.232.170.54,112.17.10.183,112.17.10.184,112.17.10.185,183.232.170.61,183.232.170.62,183.240.55.201,124.160.148.182,124.160.148.182,121.201.108.182,121.201.108.177,183.129.141.50,183.129.141.54,120.132.86.110,120.132.86.104,183.131.12.181,121.201.70.202,60.28.160.201,60.28.160.190,60.28.160.191,60.28.160.192,121.36.168.175,121.52.252.113"